In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
dataset = pd.read_csv('Train.csv')
dataset.head()

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [29]:
dataset = dataset.values

In [30]:
print(dataset.shape)

(1600, 6)


In [31]:
x = dataset[:, : 5]
y = dataset[:,5: ]
print(x.shape)
print(y.shape)

(1600, 5)
(1600, 1)


In [32]:
from sklearn.linear_model import LinearRegression

In [33]:
lr = LinearRegression()
lr.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
print(lr.coef_)
print(lr.intercept_)

[[29.68187118 92.66247759  8.28062089 44.76773522  2.51916121]]
[4.99096674]


In [35]:
test = pd.read_csv('Test.csv')
test = test.values

In [36]:
result = np.empty((test.shape[0], 2))
print(result.shape)
print(test[1])

(400, 2)
[-0.3750212   0.95318453  0.62671914  0.70440575 -0.35548921]


In [37]:
for i in range(test.shape[0]):
    curr_result = lr.intercept_ + np.dot(lr.coef_, test[i])
    result[i][0] = int(i)
    result[i][1] = curr_result
print(result[:5])

[[  0.         114.58368923]
 [  1.         118.01281466]
 [  2.         -21.73985233]
 [  3.         -43.93689854]
 [  4.         -95.91489844]]


In [38]:
print(result[:3, 0])

[0. 1. 2.]


In [43]:
df = pd.DataFrame({'Id':[i for i in range(test.shape[0])], 'target': result[:, 1]})

In [44]:
df.head()

Id      target
0   0  114.583689
1   1  118.012815
2   2  -21.739852
3   3  -43.936899
4   4  -95.914898

In [45]:
df.to_csv('Y.csv', index = False)